runtime: python312

entrypoint: gunicorn application:application -w 4 -k uvicorn.workers.UvicornWorker

instance_class: F2

env_variables:
  # These will be overridden by environment variables set in the GAE console
  # or by the deployment script
  ENVIRONMENT: "uat"
  
handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50 