export const RELATIONSHIP_TYPES = [
  'Direct',
  'Indirect',
] as const;

export const PRIMARY_DOMAINS = [
  'Business',
  'Government',
  'Religious / Spiritual',
  'Sports',
  'Entertainment & Media',
  'Education',
  'Healthcare',
] as const;

export const HONORIFIC_TITLES = [
  'Mr.',
  'Mrs.',
  'Ms.',
  'Admiral',
  'Air Chief Marshal',
  'Ambassador',
  'Apostle',
  'Bishop',
  'Brigadier General',
  'Chancellor',
  'Chief',
  'Colonel',
  'Commissioner',
  'Counsellor',
  'Dr.',
  'Elder',
  'General',
  'General (Retd.)',
  'H.E.',
  'Her Excellency the Right Honourable',
  'Her Majesty',
  'Her Worship',
  'His Eminence',
  'His Majesty',
  'His Worship',
  'Imam',
  'Justice',
  'Kami',
  'Lt. Col',
  'Pastor',
  'Priest',
  'Prof.',
  'Rabbi',
  'Right Honourable',
  'Sadhvi',
  'Sergeant',
  'Sheriff',
  'Shri',
  'Sir',
  'Smt.',
  'Sushri',
  'Swami',
  'The Honorable',
  'The Honourable',
  'The Reverend',
  'Sheikh',
] as const;

export type PrimaryDomain = typeof PRIMARY_DOMAINS[number];
export type HonorificTitle = typeof HONORIFIC_TITLES[number]; 
export type RelationshipType = typeof RELATIONSHIP_TYPES[number];