"""Adding location

Revision ID: 0b9855d40e76
Revises: 1961fa939404
Create Date: 2025-02-21 21:36:01.812634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9855d40e76'
down_revision: Union[str, None] = '1961fa939404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'locations', ['location_id'], ['id'])
    op.drop_column('appointments', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'location_id')
    # ### end Alembic commands ###
