"""Refactor AppointmentUser to AppointmentContact and remove user_id field

Revision ID: 14e225dacef3
Revises: 56bb9a297c59
Create Date: 2025-06-04 23:50:27.670644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14e225dacef3'
down_revision: Union[str, None] = '56bb9a297c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Import existing enum types
    from sqlalchemy.dialects.postgresql import ENUM
    
    # Get existing enum types (they already exist from previous migrations)
    roleinteamproject_enum = ENUM('LEAD_MEMBER', 'CORE_TEAM_MEMBER', 'OCCASIONAL_CONTRIBUTOR', 'OTHER', name='roleinteamproject', create_type=False)
    attendancestatus_enum = ENUM('PENDING', 'CHECKED_IN', 'CANCELLED', 'NO_SHOW', name='attendancestatus', create_type=False)
    
    # First, drop the old appointment_users table to free up the constraint name
    op.drop_index('idx_appointment_users_appointment_id', table_name='appointment_users')
    op.drop_index('idx_appointment_users_attendance_status', table_name='appointment_users')
    op.drop_index('idx_appointment_users_contact_id', table_name='appointment_users')
    op.drop_index('idx_appointment_users_user_id', table_name='appointment_users')
    op.drop_index('ix_appointment_users_appointment_id', table_name='appointment_users')
    op.drop_index('ix_appointment_users_attendance_status', table_name='appointment_users')
    op.drop_index('ix_appointment_users_contact_id', table_name='appointment_users')
    op.drop_index('ix_appointment_users_id', table_name='appointment_users')
    op.drop_index('ix_appointment_users_user_id', table_name='appointment_users')
    op.drop_table('appointment_users')
    
    # Now create the new appointment_contacts table
    op.create_table('appointment_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('role_in_team_project', roleinteamproject_enum, nullable=True),
    sa.Column('role_in_team_project_other', sa.String(length=255), nullable=True),
    sa.Column('attendance_status', attendancestatus_enum, nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['user_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', 'contact_id', name='unique_appointment_contact')
    )
    op.create_index('idx_appointment_contacts_appointment_id', 'appointment_contacts', ['appointment_id'], unique=False)
    op.create_index('idx_appointment_contacts_attendance_status', 'appointment_contacts', ['attendance_status'], unique=False)
    op.create_index('idx_appointment_contacts_contact_id', 'appointment_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_appointment_contacts_appointment_id'), 'appointment_contacts', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_contacts_attendance_status'), 'appointment_contacts', ['attendance_status'], unique=False)
    op.create_index(op.f('ix_appointment_contacts_contact_id'), 'appointment_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_appointment_contacts_id'), 'appointment_contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attendance_status', postgresql.ENUM('PENDING', 'CHECKED_IN', 'CANCELLED', 'NO_SHOW', name='attendancestatus'), autoincrement=False, nullable=True),
    sa.Column('checked_in_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checked_in_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_in_team_project', postgresql.ENUM('LEAD_MEMBER', 'CORE_TEAM_MEMBER', 'OCCASIONAL_CONTRIBUTOR', 'OTHER', name='roleinteamproject'), autoincrement=False, nullable=True),
    sa.Column('role_in_team_project_other', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='appointment_users_appointment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], name='appointment_users_checked_in_by_fkey'),
    sa.ForeignKeyConstraint(['contact_id'], ['user_contacts.id'], name='appointment_users_contact_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='appointment_users_created_by_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='appointment_users_updated_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='appointment_users_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='appointment_users_pkey'),
    sa.UniqueConstraint('appointment_id', 'contact_id', name='unique_appointment_contact')
    )
    op.create_index('ix_appointment_users_user_id', 'appointment_users', ['user_id'], unique=False)
    op.create_index('ix_appointment_users_id', 'appointment_users', ['id'], unique=False)
    op.create_index('ix_appointment_users_contact_id', 'appointment_users', ['contact_id'], unique=False)
    op.create_index('ix_appointment_users_attendance_status', 'appointment_users', ['attendance_status'], unique=False)
    op.create_index('ix_appointment_users_appointment_id', 'appointment_users', ['appointment_id'], unique=False)
    op.create_index('idx_appointment_users_user_id', 'appointment_users', ['user_id'], unique=False)
    op.create_index('idx_appointment_users_contact_id', 'appointment_users', ['contact_id'], unique=False)
    op.create_index('idx_appointment_users_attendance_status', 'appointment_users', ['attendance_status'], unique=False)
    op.create_index('idx_appointment_users_appointment_id', 'appointment_users', ['appointment_id'], unique=False)
    op.drop_index(op.f('ix_appointment_contacts_id'), table_name='appointment_contacts')
    op.drop_index(op.f('ix_appointment_contacts_contact_id'), table_name='appointment_contacts')
    op.drop_index(op.f('ix_appointment_contacts_attendance_status'), table_name='appointment_contacts')
    op.drop_index(op.f('ix_appointment_contacts_appointment_id'), table_name='appointment_contacts')
    op.drop_index('idx_appointment_contacts_contact_id', table_name='appointment_contacts')
    op.drop_index('idx_appointment_contacts_attendance_status', table_name='appointment_contacts')
    op.drop_index('idx_appointment_contacts_appointment_id', table_name='appointment_contacts')
    op.drop_table('appointment_contacts')
    # ### end Alembic commands ###
