"""Adding additional field for dignitary

Revision ID: 1961fa939404
Revises: 332f0a1b2559
Create Date: 2025-02-21 20:12:40.277732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1961fa939404'
down_revision: Union[str, None] = '332f0a1b2559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dignitaries', sa.Column('has_dignitary_met_gurudev', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dignitaries', 'has_dignitary_met_gurudev')
    # ### end Alembic commands ###
