"""Adding appointment date and time

Revision ID: 2cbd726efb84
Revises: 4a48b316e418
Create Date: 2025-02-14 19:50:39.264947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cbd726efb84'
down_revision: Union[str, None] = '4a48b316e418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_date', sa.Date(), nullable=True))
    op.add_column('appointments', sa.Column('appointment_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'appointment_time')
    op.drop_column('appointments', 'appointment_date')
    # ### end Alembic commands ###
