"""Updated preferred_time to an Enum

Revision ID: 332f0a1b2559
Revises: 46bedfb53e75
Create Date: 2025-02-21 18:04:58.867624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '332f0a1b2559'
down_revision: Union[str, None] = '46bedfb53e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 
        column_name='preferred_time',
        new_column_name='preferred_time_of_day',
        nullable=False
    )
    op.execute('DROP TYPE IF EXISTS appointmenttimeofday')
    appointment_time_of_day = postgresql.ENUM('MORNING', 'AFTERNOON', 'EVENING', name='appointmenttimeofday')
    appointment_time_of_day.create(op.get_bind())
    op.alter_column('appointments', 
        column_name='preferred_time_of_day',
        existing_type=sa.String(),
        type_=appointment_time_of_day,
        nullable=False,
        postgresql_using='preferred_time_of_day::appointmenttimeofday'
    )
    op.add_column('appointments', sa.Column('requester_notes_to_secretariat', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('secretariat_meeting_notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('secretariat_follow_up_actions', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('secretariat_notes_to_requester', sa.Text(), nullable=True))
    op.drop_column('appointments', 'meeting_notes')
    op.drop_column('appointments', 'pre_meeting_notes')
    op.drop_column('appointments', 'duration')
    op.drop_column('appointments', 'secretariat_comments')
    op.drop_column('appointments', 'follow_up_actions')
    op.execute('DROP TYPE IF EXISTS honorifictitle')
    honorific_title = postgresql.ENUM('MR', 'MRS', 'MS', 'ADMIRAL', 'AIR_CHIEF_MARSHAL', 'AMBASSADOR', 'APOSTLE', 'BISHOP', 'BRIGADIER_GENERAL', 'CHANCELLOR', 'CHIEF', 'COLONEL', 'COMMISSIONER', 'COUNSELLOR', 'DR', 'ELDER', 'GENERAL', 'GENERAL_RETD', 'HE', 'HER_EXCELLENCY_THE_RIGHT_HONOURABLE', 'HER_MAJESTY', 'HER_WORSHIP', 'HIS_EMINENCE', 'HIS_MAJESTY', 'HIS_WORSHIP', 'IMAM', 'JUSTICE', 'KAMI', 'LT_COL', 'PASTOR', 'PRIEST', 'PROF', 'RABBI', 'RIGHT_HONOURABLE', 'SADHVI', 'SERGEANT', 'SHERIFF', 'SHRI', 'SIR', 'SMT', 'SUSHRI', 'SWAMI', 'THE_HONORABLE', 'THE_HONOURABLE', 'THE_REVEREND', 'SHEIKH', name='honorifictitle')
    honorific_title.create(op.get_bind())
    op.alter_column('dignitaries', 'honorific_title',
        existing_type=postgresql.ENUM('MR', 'MRS', 'MS', 'ADMIRAL', 'AIR_CHIEF_MARSHAL', 'AMBASSADOR', 'APOSTLE', 'BISHOP', 'BRIGADIER_GENERAL', 'CHANCELLOR', 'CHIEF', 'COLONEL', 'COMMISSIONER', 'COUNSELLOR', 'DR', 'ELDER', 'GENERAL', 'GENERAL_RETD', 'HE', 'HER_EXCELLENCY_THE_RIGHT_HONOURABLE', 'HER_MAJESTY', 'HER_WORSHIP', 'HIS_EMINENCE', 'HIS_MAJESTY', 'HIS_WORSHIP', 'IMAM', 'JUSTICE', 'KAMI', 'LT_COL', 'PASTOR', 'PRIEST', 'PROF', 'RABBI', 'RIGHT_HONOURABLE', 'SADHVI', 'SERGEANT', 'SHERIFF', 'SHRI', 'SIR', 'SMT', 'SUSHRI', 'SWAMI', 'THE_HONORABLE', 'THE_HONOURABLE', 'THE_REVEREND', 'SHEIKH', name='dignitaryhonorifictitle'),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column('dignitaries', 'honorific_title',
        existing_type=sa.Text(),
        type_=honorific_title,
        existing_nullable=False,
        postgresql_using='honorific_title::honorifictitle'
    )
    op.execute('DROP TYPE IF EXISTS primarydomain')
    primary_domain = postgresql.ENUM('BUSINESS', 'GOVERNMENT', 'RELIGIOUS_SPIRITUAL', 'SPORTS', 'ENTERTAINMENT_MEDIA', 'EDUCATION', 'HEALTHCARE', name='primarydomain')
    primary_domain.create(op.get_bind())
    op.alter_column('dignitaries', 'primary_domain',
        existing_type=postgresql.ENUM('BUSINESS', 'GOVERNMENT', 'RELIGIOUS_SPIRITUAL', 'SPORTS', 'ENTERTAINMENT_MEDIA', 'EDUCATION', 'HEALTHCARE', name='dignitaryprimarydomain'),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column('dignitaries', 'primary_domain',
        existing_type=sa.Text(),
        type_=primary_domain,
        existing_nullable=False,
        postgresql_using='primary_domain::primarydomain'
    )
    op.alter_column('dignitaries', 'bio_summary',
        existing_type=sa.Text(),
        nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dignitaries', 'bio_summary',
        existing_type=sa.TEXT(),
        nullable=False)
    op.alter_column('dignitaries', 'primary_domain',
        existing_type=sa.Enum('BUSINESS', 'GOVERNMENT', 'RELIGIOUS_SPIRITUAL', 'SPORTS', 'ENTERTAINMENT_MEDIA', 'EDUCATION', 'HEALTHCARE', name='primarydomain'),
        type_=postgresql.ENUM('BUSINESS', 'GOVERNMENT', 'RELIGIOUS_SPIRITUAL', 'SPORTS', 'ENTERTAINMENT_MEDIA', 'EDUCATION', 'HEALTHCARE', name='dignitaryprimarydomain'),
        existing_nullable=False,
        postgresql_using='primary_domain::dignitaryprimarydomain'
    )
    op.alter_column('dignitaries', 'honorific_title',
        existing_type=sa.Enum('MR', 'MRS', 'MS', 'ADMIRAL', 'AIR_CHIEF_MARSHAL', 'AMBASSADOR', 'APOSTLE', 'BISHOP', 'BRIGADIER_GENERAL', 'CHANCELLOR', 'CHIEF', 'COLONEL', 'COMMISSIONER', 'COUNSELLOR', 'DR', 'ELDER', 'GENERAL', 'GENERAL_RETD', 'HE', 'HER_EXCELLENCY_THE_RIGHT_HONOURABLE', 'HER_MAJESTY', 'HER_WORSHIP', 'HIS_EMINENCE', 'HIS_MAJESTY', 'HIS_WORSHIP', 'IMAM', 'JUSTICE', 'KAMI', 'LT_COL', 'PASTOR', 'PRIEST', 'PROF', 'RABBI', 'RIGHT_HONOURABLE', 'SADHVI', 'SERGEANT', 'SHERIFF', 'SHRI', 'SIR', 'SMT', 'SUSHRI', 'SWAMI', 'THE_HONORABLE', 'THE_HONOURABLE', 'THE_REVEREND', 'SHEIKH', name='honorifictitle'),
        type_=postgresql.ENUM('MR', 'MRS', 'MS', 'ADMIRAL', 'AIR_CHIEF_MARSHAL', 'AMBASSADOR', 'APOSTLE', 'BISHOP', 'BRIGADIER_GENERAL', 'CHANCELLOR', 'CHIEF', 'COLONEL', 'COMMISSIONER', 'COUNSELLOR', 'DR', 'ELDER', 'GENERAL', 'GENERAL_RETD', 'HE', 'HER_EXCELLENCY_THE_RIGHT_HONOURABLE', 'HER_MAJESTY', 'HER_WORSHIP', 'HIS_EMINENCE', 'HIS_MAJESTY', 'HIS_WORSHIP', 'IMAM', 'JUSTICE', 'KAMI', 'LT_COL', 'PASTOR', 'PRIEST', 'PROF', 'RABBI', 'RIGHT_HONOURABLE', 'SADHVI', 'SERGEANT', 'SHERIFF', 'SHRI', 'SIR', 'SMT', 'SUSHRI', 'SWAMI', 'THE_HONORABLE', 'THE_HONOURABLE', 'THE_REVEREND', 'SHEIKH', name='dignitaryhonorifictitle'),
        existing_nullable=False,
        postgresql_using='honorific_title::dignitaryhonorifictitle'
    )
    op.add_column('appointments', sa.Column('follow_up_actions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('secretariat_comments', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('pre_meeting_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('meeting_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'secretariat_notes_to_requester')
    op.drop_column('appointments', 'secretariat_follow_up_actions')
    op.drop_column('appointments', 'secretariat_meeting_notes')
    op.drop_column('appointments', 'requester_notes_to_secretariat')
    op.alter_column('appointments', 'preferred_time_of_day',
        existing_type=sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='appointmenttimeofday'),
        type_=sa.String(),
        nullable=False
    )
    op.alter_column('appointments', 'preferred_time_of_day',
        new_column_name='preferred_time',
        nullable=False
    )
    # ### end Alembic commands ###
