"""Updating appointment for dignitary insert

Revision ID: 3437158edb29
Revises: c6397be39202
Create Date: 2025-03-23 13:26:05.987353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3437158edb29'
down_revision: Union[str, None] = 'c6397be39202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'appointments', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'created_by')
    # ### end Alembic commands ###
