"""Updating datamodel for darshan functionality

Revision ID: 4e508ec19aac
Revises: afd5e22a102e
Create Date: 2025-05-31 19:02:42.704303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e508ec19aac'
down_revision: Union[str, None] = 'afd5e22a102e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_users', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('appointment_users', sa.Column('role_in_team_project', sa.Enum('LEAD_MEMBER', 'CORE_TEAM_MEMBER', 'OCCASIONAL_CONTRIBUTOR', 'OTHER', name='roleinteamproject'), nullable=True))
    op.add_column('appointment_users', sa.Column('role_in_team_project_other', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_users', 'role_in_team_project_other')
    op.drop_column('appointment_users', 'role_in_team_project')
    op.drop_column('appointment_users', 'last_name')
    # ### end Alembic commands ###
