"""Adding user_contact table

Revision ID: 56bb9a297c59
Revises: ebea4f0173c2
Create Date: 2025-06-04 22:47:31.601440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56bb9a297c59'
down_revision: Union[str, None] = 'ebea4f0173c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_users', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_appointment_user', 'appointment_users', type_='unique')
    op.create_index('idx_appointment_users_contact_id', 'appointment_users', ['contact_id'], unique=False)
    op.create_index(op.f('ix_appointment_users_contact_id'), 'appointment_users', ['contact_id'], unique=False)
    op.create_unique_constraint('unique_appointment_contact', 'appointment_users', ['appointment_id', 'contact_id'])
    op.create_foreign_key(None, 'appointment_users', 'user_contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appointment_users', 'phone')
    op.drop_column('appointment_users', 'first_name')
    op.drop_column('appointment_users', 'email')
    op.drop_column('appointment_users', 'relationship_to_requester')
    op.drop_column('appointment_users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_users', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('appointment_users', sa.Column('relationship_to_requester', postgresql.ENUM('SPOUSE', 'CHILD', 'PARENT', 'RELATIVE', 'FRIEND', 'OTHER', name='personrelationshiptype'), autoincrement=False, nullable=True))
    op.add_column('appointment_users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('appointment_users', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('appointment_users', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointment_users', type_='foreignkey')
    op.drop_constraint('unique_appointment_contact', 'appointment_users', type_='unique')
    op.drop_index(op.f('ix_appointment_users_contact_id'), table_name='appointment_users')
    op.drop_index('idx_appointment_users_contact_id', table_name='appointment_users')
    op.create_unique_constraint('unique_appointment_user', 'appointment_users', ['appointment_id', 'user_id'])
    op.drop_column('appointment_users', 'contact_id')
    # ### end Alembic commands ###
