"""Adding meeting place to appointment

Revision ID: 6b1dad02b702
Revises: 583e4907f051
Create Date: 2025-04-18 00:36:06.698967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1dad02b702'
down_revision: Union[str, None] = '583e4907f051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meeting_place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'meeting_places', ['meeting_place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'meeting_place_id')
    # ### end Alembic commands ###
