"""Adding additional dignitary fields

Revision ID: 6b25c8d72b2e
Revises: update_appointment_enums
Create Date: 2025-03-19 22:51:06.775638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b25c8d72b2e'
down_revision: Union[str, None] = 'update_appointment_enums'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'sub_status',
               existing_type=postgresql.ENUM('CANCELLED', 'FOLLOW_UP_REQUIRED', 'LOW_PRIORITY', 'MET_GURUDEV', 'NEED_MORE_INFO', 'NEED_RESCHEDULE', 'NO_FURTHER_ACTION', 'NOT_REVIEWED', 'SHORTLISTED', 'UNDER_CONSIDERATION', 'UNSCHEDULED', 'SCHEDULED', name='appointmentsubstatus'),
               nullable=True)
    op.add_column('dignitaries', sa.Column('other_phone', sa.String(), nullable=True))
    op.add_column('dignitaries', sa.Column('fax', sa.String(), nullable=True))
    op.add_column('dignitaries', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('dignitaries', sa.Column('social_media', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('dignitaries', sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dignitaries', 'additional_info')
    op.drop_column('dignitaries', 'social_media')
    op.drop_column('dignitaries', 'street_address')
    op.drop_column('dignitaries', 'fax')
    op.drop_column('dignitaries', 'other_phone')
    op.alter_column('appointments', 'sub_status',
               existing_type=postgresql.ENUM('CANCELLED', 'FOLLOW_UP_REQUIRED', 'LOW_PRIORITY', 'MET_GURUDEV', 'NEED_MORE_INFO', 'NEED_RESCHEDULE', 'NO_FURTHER_ACTION', 'NOT_REVIEWED', 'SHORTLISTED', 'UNDER_CONSIDERATION', 'UNSCHEDULED', 'SCHEDULED', name='appointmentsubstatus'),
               nullable=False)
    # ### end Alembic commands ###
