"""Adding dignitary Gurudev meeting details

Revision ID: 6c0203b2d7e3
Revises: 0b9855d40e76
Create Date: 2025-02-24 00:25:53.358984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0203b2d7e3'
down_revision: Union[str, None] = '0b9855d40e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dignitaries', sa.Column('gurudev_meeting_date', sa.Date(), nullable=True))
    op.add_column('dignitaries', sa.Column('gurudev_meeting_location', sa.String(), nullable=True))
    op.add_column('dignitaries', sa.Column('gurudev_meeting_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dignitaries', 'gurudev_meeting_notes')
    op.drop_column('dignitaries', 'gurudev_meeting_location')
    op.drop_column('dignitaries', 'gurudev_meeting_date')
    # ### end Alembic commands ###
