"""Adding attendance status to AppointmentDignitary

Revision ID: 783ae9f039c0
Revises: 44436013c6cc
Create Date: 2025-04-06 13:29:45.129989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783ae9f039c0'
down_revision: Union[str, None] = '44436013c6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_dignitaries', sa.Column('attendance_status', sa.Enum('PENDING', 'CHECKED_IN', 'CANCELLED', 'NO_SHOW', name='attendancestatus'), nullable=True))
    op.alter_column('users', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('appointment_dignitaries', 'attendance_status')
    # ### end Alembic commands ###
