"""Adding created and updated fields to AppointmentDignitary

Revision ID: 801d09330ada
Revises: 783ae9f039c0
Create Date: 2025-04-06 14:51:55.828287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801d09330ada'
down_revision: Union[str, None] = '783ae9f039c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_dignitaries', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('appointment_dignitaries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('appointment_dignitaries', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment_dignitaries', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'appointment_dignitaries', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment_dignitaries', type_='foreignkey')
    op.drop_constraint(None, 'appointment_dignitaries', type_='foreignkey')
    op.drop_column('appointment_dignitaries', 'updated_by')
    op.drop_column('appointment_dignitaries', 'updated_at')
    op.drop_column('appointment_dignitaries', 'created_by')
    # ### end Alembic commands ###
