"""Adding timezone information to location

Revision ID: 9906cb768609
Revises: aa4d386be8d9
Create Date: 2025-03-27 05:25:18.665181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9906cb768609'
down_revision: Union[str, None] = 'aa4d386be8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'timezone')
    # ### end Alembic commands ###
