"""Adding access control attributes

Revision ID: a2714f03ae7e
Revises: d87ea5328426
Create Date: 2025-03-21 22:06:36.588663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'a2714f03ae7e'
down_revision: Union[str, None] = 'd87ea5328426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add columns as nullable first
    op.add_column('dignitaries', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('country_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country_code', sa.String(), nullable=True))
    
    # Step 2: Update existing records with default value "US"
    op.execute(text("UPDATE dignitaries SET country_code = 'US' WHERE country_code IS NULL"))
    op.execute(text("UPDATE locations SET country_code = 'US' WHERE country_code IS NULL"))
    op.execute(text("UPDATE users SET country_code = 'US' WHERE country_code IS NULL"))
    
    # Step 3: Alter columns to be NOT NULL where needed
    op.alter_column('locations', 'country_code', nullable=False)
    op.alter_column('users', 'country_code', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country_code')
    op.drop_column('locations', 'country_code')
    op.drop_column('dignitaries', 'country_code')
    # ### end Alembic commands ###
