"""Updating appointment for dignitary insert

Revision ID: aa4d386be8d9
Revises: 3437158edb29
Create Date: 2025-03-23 14:55:45.997085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa4d386be8d9'
down_revision: Union[str, None] = '3437158edb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'purpose',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('appointments', 'preferred_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('appointments', 'preferred_time_of_day',
               existing_type=postgresql.ENUM('MORNING', 'AFTERNOON', 'EVENING', name='appointmenttimeofday'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'preferred_time_of_day',
               existing_type=postgresql.ENUM('MORNING', 'AFTERNOON', 'EVENING', name='appointmenttimeofday'),
               nullable=False)
    op.alter_column('appointments', 'preferred_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('appointments', 'purpose',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
