"""Adding location fields

Revision ID: bd3354258ff1
Revises: 3f4a5b6c7d8e
Create Date: 2025-02-25 22:22:41.111098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3354258ff1'
down_revision: Union[str, None] = '3f4a5b6c7d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointment_attachments_id'), 'appointment_attachments', ['id'], unique=False)
    op.add_column('locations', sa.Column('attachment_path', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('attachment_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'attachment_name')
    op.drop_column('locations', 'attachment_path')
    op.drop_index(op.f('ix_appointment_attachments_id'), table_name='appointment_attachments')
    # ### end Alembic commands ###
