"""rename_thumbnail_path_to_attachment_thumbnail_path

Revision ID: bfa9502163e7
Revises: f84273165203
Create Date: 2025-02-25 22:41:48.392215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa9502163e7'
down_revision: Union[str, None] = 'f84273165203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('attachment_thumbnail_path', sa.String(), nullable=True))
    
    # Copy data from the old column to the new column
    op.execute('UPDATE locations SET attachment_thumbnail_path = thumbnail_path')
    
    op.drop_column('locations', 'thumbnail_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('thumbnail_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Copy data from the new column to the old column
    op.execute('UPDATE locations SET thumbnail_path = attachment_thumbnail_path')
    
    op.drop_column('locations', 'attachment_thumbnail_path')
    # ### end Alembic commands ###
