"""Updating datamodel for darshan functionality

Revision ID: bfcf341da94d
Revises: e8d3d84d47f6
Create Date: 2025-06-03 07:30:00.745835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfcf341da94d'
down_revision: Union[str, None] = 'e8d3d84d47f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
