"""Adding new user role

Revision ID: c6397be39202
Revises: add_countries_table
Create Date: 2025-03-22 06:19:08.097852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6397be39202'
down_revision: Union[str, None] = 'add_countries_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'ADMIN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Can't remove enum value in PostgreSQL, would need to create a new enum without ADMIN
    # and swap the columns to use it, then drop the old enum. Leaving as-is since downgrading
    # with existing ADMIN values would cause errors anyway.
    pass
    # ### end Alembic commands ###
