"""Add attachment_type to AppointmentAttachment

Revision ID: d16962760db2
Revises: bfa9502163e7
Create Date: 2025-02-26 01:20:00.257761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd16962760db2'
down_revision: Union[str, None] = 'bfa9502163e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    attachment_type_enum = postgresql.ENUM('GENERAL', 'BUSINESS_CARD', name='attachmenttype')
    attachment_type_enum.create(op.get_bind())
    
    op.add_column('appointment_attachments', sa.Column('attachment_type', sa.Enum('GENERAL', 'BUSINESS_CARD', name='attachmenttype'), server_default='GENERAL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointment_attachments', 'attachment_type')
    
    # Drop the enum type
    attachment_type_enum = postgresql.ENUM('GENERAL', 'BUSINESS_CARD', name='attachmenttype')
    attachment_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
