"""Adding business card fields for dignitary

Revision ID: d1ab9b66932b
Revises: 6b25c8d72b2e
Create Date: 2025-03-19 23:00:43.593843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ab9b66932b'
down_revision: Union[str, None] = '6b25c8d72b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dignitaries', sa.Column('business_card_file_name', sa.String(), nullable=True))
    op.add_column('dignitaries', sa.Column('business_card_file_path', sa.String(), nullable=True))
    op.add_column('dignitaries', sa.Column('business_card_file_type', sa.String(), nullable=True))
    op.add_column('dignitaries', sa.Column('business_card_is_image', sa.Boolean(), nullable=True))
    op.add_column('dignitaries', sa.Column('business_card_thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dignitaries', 'business_card_thumbnail_path')
    op.drop_column('dignitaries', 'business_card_is_image')
    op.drop_column('dignitaries', 'business_card_file_type')
    op.drop_column('dignitaries', 'business_card_file_path')
    op.drop_column('dignitaries', 'business_card_file_name')
    # ### end Alembic commands ###
