"""Adding timezone information to country

Revision ID: d6e4bc6e1f61
Revises: 9906cb768609
Create Date: 2025-03-27 05:51:58.456013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e4bc6e1f61'
down_revision: Union[str, None] = '9906cb768609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('timezones', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('countries', sa.Column('default_timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'default_timezone')
    op.drop_column('countries', 'timezones')
    # ### end Alembic commands ###
