"""Adding secretariat_notes to dignitary

Revision ID: d87ea5328426
Revises: d1ab9b66932b
Create Date: 2025-03-20 01:03:35.044161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87ea5328426'
down_revision: Union[str, None] = 'd1ab9b66932b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dignitaries', sa.Column('secretariat_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dignitaries', 'secretariat_notes')
    # ### end Alembic commands ###
