"""Adding substatus and appointment type fields to appointment

Revision ID: deb8a5f1c13f
Revises: 6c0203b2d7e3
Create Date: 2025-02-24 01:15:56.600931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb8a5f1c13f'
down_revision: Union[str, None] = '6c0203b2d7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('sub_status', sa.Enum('CANCELLED', 'DARSHAN_LINE', 'FOLLOW_UP_REQUIRED', 'LOW_PRIORITY', 'MET_GURUDEV', 'NEED_MORE_INFO', 'NEED_RESCHEDULE', 'NO_FURTHER_ACTION', 'NOT_REVIEWED', 'SHORTLISTED', 'UNDER_CONSIDERATION', 'UNSCHEDULED', 'SCHEDULED', name='appointmentsubstatus'), nullable=True))
    op.add_column('appointments', sa.Column('appointment_type', sa.Enum('PRIVATE', 'SMALL_GROUP', name='appointmenttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'appointment_type')
    op.drop_column('appointments', 'sub_status')
    # ### end Alembic commands ###
