"""Updating datamodel for darshan functionality

Revision ID: e8d3d84d47f6
Revises: fcf40824696b
Create Date: 2025-06-03 06:39:35.748491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d3d84d47f6'
down_revision: Union[str, None] = 'fcf40824696b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('creation_context', sa.Enum('ADMIN', 'APPOINTMENT', 'CALENDAR_IMPORT', name='calendarcreationcontext'), nullable=True))
    op.add_column('calendar_events', sa.Column('creation_context_id', sa.String(length=255), nullable=True))
    op.create_index('idx_calendar_events_creation_context', 'calendar_events', ['creation_context', 'creation_context_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_calendar_events_creation_context', table_name='calendar_events')
    op.drop_column('calendar_events', 'creation_context_id')
    op.drop_column('calendar_events', 'creation_context')
    # ### end Alembic commands ###
