"""Adding subdivisions table

Revision ID: ebea4f0173c2
Revises: ff5627a48a3a
Create Date: 2025-06-04 07:58:09.075484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebea4f0173c2'
down_revision: Union[str, None] = 'ff5627a48a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subdivisions_country_code', table_name='subdivisions')
    op.drop_index('ix_subdivisions_id', table_name='subdivisions')
    op.drop_index('ix_subdivisions_name', table_name='subdivisions')
    op.drop_index('ix_subdivisions_subdivision_code', table_name='subdivisions')
    op.drop_index('ix_subdivisions_subdivision_type', table_name='subdivisions')
    op.drop_table('subdivisions')
    op.drop_index('ix_countries_iso2_code', table_name='countries')
    op.drop_index('ix_countries_iso3_code', table_name='countries')
    op.drop_index('ix_countries_name', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('iso2_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('iso3_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sub_region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intermediate_region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_groups', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('alt_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('timezones', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('default_timezone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('iso2_code', name='countries_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_countries_name', 'countries', ['name'], unique=False)
    op.create_index('ix_countries_iso3_code', 'countries', ['iso3_code'], unique=False)
    op.create_index('ix_countries_iso2_code', 'countries', ['iso2_code'], unique=False)
    op.create_table('subdivisions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('subdivision_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subdivision_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.iso2_code'], name='subdivisions_country_code_fkey'),
    sa.PrimaryKeyConstraint('id', name='subdivisions_pkey')
    )
    op.create_index('ix_subdivisions_subdivision_type', 'subdivisions', ['subdivision_type'], unique=False)
    op.create_index('ix_subdivisions_subdivision_code', 'subdivisions', ['subdivision_code'], unique=False)
    op.create_index('ix_subdivisions_name', 'subdivisions', ['name'], unique=False)
    op.create_index('ix_subdivisions_id', 'subdivisions', ['id'], unique=False)
    op.create_index('ix_subdivisions_country_code', 'subdivisions', ['country_code'], unique=False)
    # ### end Alembic commands ###
