"""Add appointment admin fields and status enum

Revision ID: edd54ad45525
Revises: 63fb21fa0c61
Create Date: 2025-02-14 01:04:06.653902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd54ad45525'
down_revision: Union[str, None] = '63fb21fa0c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meeting_notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('follow_up_actions', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('secretariat_comments', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('approved_date', sa.Date(), nullable=True))
    op.add_column('appointments', sa.Column('approved_time', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('last_updated_by', sa.Integer(), nullable=True))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FOLLOW_UP', name='appointmentstatus'),
               nullable=False)
    op.create_foreign_key(None, 'appointments', 'users', ['last_updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'FOLLOW_UP', name='appointmentstatus'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('appointments', 'last_updated_by')
    op.drop_column('appointments', 'approved_time')
    op.drop_column('appointments', 'approved_date')
    op.drop_column('appointments', 'secretariat_comments')
    op.drop_column('appointments', 'follow_up_actions')
    op.drop_column('appointments', 'meeting_notes')
    # ### end Alembic commands ###
