"""add_thumbnail_path_to_locations

Revision ID: f84273165203
Revises: bd3354258ff1
Create Date: 2025-02-25 22:37:43.692623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84273165203'
down_revision: Union[str, None] = 'bd3354258ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('thumbnail_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'thumbnail_path')
    # ### end Alembic commands ###
