"""Adding additional user attributes

Revision ID: ff5627a48a3a
Revises: bfcf341da94d
Create Date: 2025-06-03 22:45:27.746826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5627a48a3a'
down_revision: Union[str, None] = 'bfcf341da94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('title_in_organization', sa.String(), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state_province', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state_province_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('teacher_status', sa.Enum('NOT_TEACHER', 'PART_TIME', 'FULL_TIME', name='aolteacherstatus'), nullable=True))
    op.add_column('users', sa.Column('teacher_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('programs_taught', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('aol_affiliations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aol_affiliations')
    op.drop_column('users', 'programs_taught')
    op.drop_column('users', 'teacher_code')
    op.drop_column('users', 'teacher_status')
    op.drop_column('users', 'city')
    op.drop_column('users', 'state_province_code')
    op.drop_column('users', 'state_province')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'title_in_organization')
    # ### end Alembic commands ###
